on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

env:
    RUSTFLAGS: -D warnings
    IS_NIGHTLY: ${{ github.event_name == 'schedule' }}
    CARGO_TERM_COLOR: always

name: Consensus hive tests
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - run: mkdir artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export reth image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: paradigmxyz/reth:main
          outputs: type=docker,dest=./artifacts/reth_image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # TODO: replace when we are not using a fork
      - name: Checkout hive tests
        uses: actions/checkout@v3
        with:
          repository: paradigmxyz/hive
          ref: master
          path: hivetests

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'
      - run: go version
      - name: Build hive tool
        run: |
          cd hivetests
          go build .
          mv ./hive ../artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts


  test:
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [true]
        sim: [ethereum/consensus]
      fail-fast: false
    needs: prepare
    name: run
    runs-on: ubuntu-latest
    # TODO: pretty sure this is github's usage limit
    # might need a self hosted runner
    timeout-minutes: 360

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/reth_image.tar
          docker image ls -a
      - name: Move hive binary
        run: |
          mv /tmp/hive /usr/local/bin
          chmod +x /usr/local/bin/hive

      # TODO: replace when we are not using a fork
      - name: Checkout hive tests
        uses: actions/checkout@v3
        with:
          repository: paradigmxyz/hive
          ref: master
          path: hivetests

      - name: Run ${{ matrix.sim }} simulator
        run: |
          cd hivetests
          hive --sim "${{ matrix.sim }}$" --sim.limit "${{ matrix.limit }}" --client reth

      - name: Print simulator output
        if: ${{ failure() }}
        run: |
          cat hivetests/workspace/logs/*simulator*.log

      - name: Print reth client logs
        if: ${{ failure() }}
        run: |
          cat hivetests/workspace/logs/reth/client-*.log
